FROM confluentinc/cp-server-connect:8.3.1

USER root

RUN confluent-hub install --no-prompt \
    confluentinc/kafka-connect-jdbc:10.9.0 \
    && confluent-hub install --no-prompt \
    debezium/debezium-connector-postgresql:3.1.2

USER 1001